// Wisdom of the Ages — 500+ historical quotes
// Categories: war, leadership, philosophy, empire, faith, strategy, virtue, ambition
const QUOTES = [
// === ROMAN ===
{q:"Veni, vidi, vici.",a:"Julius Caesar",era:"100–44 BC",civ:"Roman Republic",cat:["war","ambition"]},
{q:"The die is cast.",a:"Julius Caesar",era:"100–44 BC",civ:"Roman Republic",cat:["ambition","leadership"]},
{q:"It is better to create than to learn! Creating is the essence of life.",a:"Julius Caesar",era:"100–44 BC",civ:"Roman Republic",cat:["ambition","philosophy"]},
{q:"Experience is the teacher of all things.",a:"Julius Caesar",era:"100–44 BC",civ:"Roman Republic",cat:["philosophy"]},
{q:"In war, events of importance are the result of trivial causes.",a:"Julius Caesar",era:"100–44 BC",civ:"Roman Republic",cat:["war","strategy"]},
{q:"I love the name of honor more than I fear death.",a:"Julius Caesar",era:"100–44 BC",civ:"Roman Republic",cat:["virtue","war"]},
{q:"Men willingly believe what they wish.",a:"Julius Caesar",era:"100–44 BC",civ:"Roman Republic",cat:["philosophy","strategy"]},
{q:"If you must break the law, do it to seize power: in all other cases observe it.",a:"Julius Caesar",era:"100–44 BC",civ:"Roman Republic",cat:["leadership","empire"]},
{q:"I found Rome a city of bricks and left it a city of marble.",a:"Augustus Caesar",era:"63 BC–14 AD",civ:"Roman Empire",cat:["empire","leadership"]},
{q:"Make haste slowly.",a:"Augustus Caesar",era:"63 BC–14 AD",civ:"Roman Empire",cat:["strategy","leadership"]},
{q:"Have I played the part well? Then applaud as I exit.",a:"Augustus Caesar",era:"63 BC–14 AD",civ:"Roman Empire",cat:["philosophy"]},
{q:"Young men, hear an old man to whom old men hearkened when he was young.",a:"Augustus Caesar",era:"63 BC–14 AD",civ:"Roman Empire",cat:["leadership"]},
{q:"The object of war is not to die for your country but to make the other bastard die for his.",a:"attributed to various Roman generals",era:"Classical",civ:"Roman Empire",cat:["war","strategy"]},
{q:"Let them hate, so long as they fear.",a:"Caligula (quoting Accius)",era:"12–41 AD",civ:"Roman Empire",cat:["empire","leadership"]},
{q:"While I live, let the earth be shaken with fire.",a:"Caligula",era:"12–41 AD",civ:"Roman Empire",cat:["empire"]},
{q:"What an artist dies in me!",a:"Nero",era:"37–68 AD",civ:"Roman Empire",cat:["philosophy"]},
{q:"It is not the strongest of the species that survives, but the one most responsive to change.",a:"Seneca (paraphrased)",era:"4 BC–65 AD",civ:"Roman Empire",cat:["philosophy","strategy"]},
{q:"Luck is what happens when preparation meets opportunity.",a:"Seneca",era:"4 BC–65 AD",civ:"Roman Empire",cat:["strategy","ambition"]},
{q:"We suffer more often in imagination than in reality.",a:"Seneca",era:"4 BC–65 AD",civ:"Roman Empire",cat:["philosophy","virtue"]},
{q:"It is not that we have a short time to live, but that we waste a great deal of it.",a:"Seneca",era:"4 BC–65 AD",civ:"Roman Empire",cat:["philosophy"]},
{q:"Difficulties strengthen the mind, as labor does the body.",a:"Seneca",era:"4 BC–65 AD",civ:"Roman Empire",cat:["virtue","philosophy"]},
{q:"A gem cannot be polished without friction, nor a man perfected without trials.",a:"Seneca",era:"4 BC–65 AD",civ:"Roman Empire",cat:["virtue"]},
{q:"Religion is regarded by the common people as true, by the wise as false, and by rulers as useful.",a:"Seneca",era:"4 BC–65 AD",civ:"Roman Empire",cat:["philosophy","empire"]},
{q:"The whole future lies in uncertainty: live immediately.",a:"Seneca",era:"4 BC–65 AD",civ:"Roman Empire",cat:["philosophy"]},
{q:"You have power over your mind — not outside events. Realize this, and you will find strength.",a:"Marcus Aurelius",era:"121–180 AD",civ:"Roman Empire",cat:["philosophy","virtue"]},
{q:"The happiness of your life depends upon the quality of your thoughts.",a:"Marcus Aurelius",era:"121–180 AD",civ:"Roman Empire",cat:["philosophy"]},
{q:"Waste no more time arguing about what a good man should be. Be one.",a:"Marcus Aurelius",era:"121–180 AD",civ:"Roman Empire",cat:["virtue","philosophy"]},
{q:"The best revenge is to be unlike him who performed the injury.",a:"Marcus Aurelius",era:"121–180 AD",civ:"Roman Empire",cat:["virtue"]},
{q:"Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",a:"Marcus Aurelius",era:"121–180 AD",civ:"Roman Empire",cat:["philosophy"]},
{q:"It is not death that a man should fear, but he should fear never beginning to live.",a:"Marcus Aurelius",era:"121–180 AD",civ:"Roman Empire",cat:["philosophy","ambition"]},
{q:"When you arise in the morning think of what a privilege it is to be alive.",a:"Marcus Aurelius",era:"121–180 AD",civ:"Roman Empire",cat:["philosophy"]},
{q:"The impediment to action advances action. What stands in the way becomes the way.",a:"Marcus Aurelius",era:"121–180 AD",civ:"Roman Empire",cat:["philosophy","strategy"]},
{q:"Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.",a:"Marcus Aurelius",era:"121–180 AD",civ:"Roman Empire",cat:["philosophy"]},
{q:"If it is not right do not do it; if it is not true do not say it.",a:"Marcus Aurelius",era:"121–180 AD",civ:"Roman Empire",cat:["virtue"]},
{q:"How much more grievous are the consequences of anger than the causes of it.",a:"Marcus Aurelius",era:"121–180 AD",civ:"Roman Empire",cat:["virtue","philosophy"]},
{q:"Accept the things to which fate binds you, and love the people with whom fate brings you together.",a:"Marcus Aurelius",era:"121–180 AD",civ:"Roman Empire",cat:["philosophy","virtue"]},
{q:"No man is free who is not master of himself.",a:"Epictetus",era:"50–135 AD",civ:"Roman Empire",cat:["philosophy","virtue"]},
{q:"First say to yourself what you would be; and then do what you have to do.",a:"Epictetus",era:"50–135 AD",civ:"Roman Empire",cat:["ambition","virtue"]},
{q:"Wealth consists not in having great possessions, but in having few wants.",a:"Epictetus",era:"50–135 AD",civ:"Roman Empire",cat:["philosophy","virtue"]},
{q:"Make the best use of what is in your power, and take the rest as it happens.",a:"Epictetus",era:"50–135 AD",civ:"Roman Empire",cat:["philosophy","strategy"]},
{q:"Only the educated are free.",a:"Epictetus",era:"50–135 AD",civ:"Roman Empire",cat:["philosophy"]},
{q:"I am not afraid of an army of lions led by a sheep; I am afraid of an army of sheep led by a lion.",a:"Alexander the Great",era:"356–323 BC",civ:"Macedonia",cat:["war","leadership"]},
{q:"There is nothing impossible to him who will try.",a:"Alexander the Great",era:"356–323 BC",civ:"Macedonia",cat:["ambition"]},
{q:"A tomb now suffices him for whom the whole world was not sufficient.",a:"epitaph of Alexander the Great",era:"356–323 BC",civ:"Macedonia",cat:["philosophy","empire"]},
{q:"Remember, upon the conduct of each depends the fate of all.",a:"Alexander the Great",era:"356–323 BC",civ:"Macedonia",cat:["leadership","war"]},
{q:"Heaven cannot brook two suns, nor earth two masters.",a:"Alexander the Great",era:"356–323 BC",civ:"Macedonia",cat:["empire","ambition"]},
{q:"Fortune favors the bold.",a:"Virgil",era:"70–19 BC",civ:"Roman Republic",cat:["ambition","war"]},
{q:"I fear the Greeks, even bearing gifts.",a:"Virgil",era:"70–19 BC",civ:"Roman Republic",cat:["strategy"]},
{q:"Carthage must be destroyed.",a:"Cato the Elder",era:"234–149 BC",civ:"Roman Republic",cat:["war","empire"]},
{q:"I think, therefore I am a soldier of Rome.",a:"Roman military saying",era:"Classical",civ:"Roman Empire",cat:["war","virtue"]},
{q:"The sinews of war are infinite money.",a:"Cicero",era:"106–43 BC",civ:"Roman Republic",cat:["war","strategy"]},
{q:"A nation can survive its fools, and even the ambitious. But it cannot survive treason from within.",a:"Cicero",era:"106–43 BC",civ:"Roman Republic",cat:["empire","strategy"]},
{q:"The authority of those who teach is often an obstacle to those who want to learn.",a:"Cicero",era:"106–43 BC",civ:"Roman Republic",cat:["philosophy"]},
{q:"More law, less justice.",a:"Cicero",era:"106–43 BC",civ:"Roman Republic",cat:["philosophy","empire"]},
{q:"The life of the dead is placed in the memory of the living.",a:"Cicero",era:"106–43 BC",civ:"Roman Republic",cat:["philosophy"]},
{q:"If you have a garden and a library, you have everything you need.",a:"Cicero",era:"106–43 BC",civ:"Roman Republic",cat:["philosophy"]},
{q:"While the sick man has life, there is hope.",a:"Cicero",era:"106–43 BC",civ:"Roman Republic",cat:["philosophy","virtue"]},
{q:"Silent enim leges inter arma — In times of war, the law falls silent.",a:"Cicero",era:"106–43 BC",civ:"Roman Republic",cat:["war","empire"]},
{q:"Hannibal is at the gates!",a:"Roman saying",era:"218 BC",civ:"Roman Republic",cat:["war"]},
{q:"I will either find a way or make one.",a:"Hannibal Barca",era:"247–183 BC",civ:"Carthage",cat:["ambition","war","strategy"]},
{q:"We will either find a way, or make one.",a:"Hannibal Barca",era:"247–183 BC",civ:"Carthage",cat:["ambition","strategy"]},
{q:"Woe to the vanquished.",a:"Brennus",era:"390 BC",civ:"Gaul",cat:["war","empire"]},
{q:"The brave man is not he who does not feel afraid, but he who conquers that fear.",a:"Plutarch",era:"46–120 AD",civ:"Roman Empire",cat:["virtue","war"]},
{q:"What we achieve inwardly will change outer reality.",a:"Plutarch",era:"46–120 AD",civ:"Roman Empire",cat:["philosophy"]},
// === GREEK ===
{q:"Know thyself.",a:"Inscription at Delphi",era:"Ancient Greece",civ:"Greece",cat:["philosophy"]},
{q:"The unexamined life is not worth living.",a:"Socrates",era:"470–399 BC",civ:"Athens",cat:["philosophy"]},
{q:"I know that I know nothing.",a:"Socrates",era:"470–399 BC",civ:"Athens",cat:["philosophy"]},
{q:"Strong minds discuss ideas, average minds discuss events, weak minds discuss people.",a:"Socrates",era:"470–399 BC",civ:"Athens",cat:["philosophy"]},
{q:"He is richest who is content with the least, for contentment is the wealth of nature.",a:"Socrates",era:"470–399 BC",civ:"Athens",cat:["philosophy","virtue"]},
{q:"We are what we repeatedly do. Excellence, then, is not an act, but a habit.",a:"Aristotle",era:"384–322 BC",civ:"Athens",cat:["virtue","philosophy"]},
{q:"The whole is greater than the sum of its parts.",a:"Aristotle",era:"384–322 BC",civ:"Athens",cat:["philosophy"]},
{q:"It is the mark of an educated mind to be able to entertain a thought without accepting it.",a:"Aristotle",era:"384–322 BC",civ:"Athens",cat:["philosophy"]},
{q:"Courage is the first of human qualities because it is the quality which guarantees the others.",a:"Aristotle",era:"384–322 BC",civ:"Athens",cat:["virtue"]},
{q:"Knowing yourself is the beginning of all wisdom.",a:"Aristotle",era:"384–322 BC",civ:"Athens",cat:["philosophy"]},
{q:"Only the dead have seen the end of war.",a:"Plato",era:"428–348 BC",civ:"Athens",cat:["war","philosophy"]},
{q:"The measure of a man is what he does with power.",a:"Plato",era:"428–348 BC",civ:"Athens",cat:["leadership","philosophy"]},
{q:"Good people do not need laws to tell them to act responsibly, while bad people will find a way around the laws.",a:"Plato",era:"428–348 BC",civ:"Athens",cat:["philosophy","empire"]},
{q:"Be kind, for everyone you meet is fighting a hard battle.",a:"Plato",era:"428–348 BC",civ:"Athens",cat:["virtue"]},
{q:"Come back with your shield — or on it.",a:"Spartan mothers",era:"Classical",civ:"Sparta",cat:["war","virtue"]},
{q:"Molon labe — Come and take them.",a:"Leonidas I",era:"540–480 BC",civ:"Sparta",cat:["war","virtue"]},
{q:"If.",a:"Spartans (reply to Philip II's threat)",era:"346 BC",civ:"Sparta",cat:["war","strategy"]},
{q:"The nation that makes a great distinction between its scholars and its warriors will have its thinking done by cowards and its fighting done by fools.",a:"Thucydides",era:"460–400 BC",civ:"Athens",cat:["war","philosophy","empire"]},
{q:"The strong do what they can and the weak suffer what they must.",a:"Thucydides",era:"460–400 BC",civ:"Athens",cat:["empire","strategy"]},
{q:"The secret of happiness is freedom, and the secret of freedom is courage.",a:"Thucydides",era:"460–400 BC",civ:"Athens",cat:["philosophy","virtue"]},
{q:"History is philosophy teaching by examples.",a:"Thucydides",era:"460–400 BC",civ:"Athens",cat:["philosophy"]},
{q:"Out of every one hundred men, ten shouldn't even be there, eighty are just targets, nine are the real fighters. Ah, but the one — one is a warrior.",a:"Heraclitus",era:"535–475 BC",civ:"Greece",cat:["war","virtue"]},
{q:"No man ever steps in the same river twice, for it's not the same river and he's not the same man.",a:"Heraclitus",era:"535–475 BC",civ:"Greece",cat:["philosophy"]},
{q:"Character is destiny.",a:"Heraclitus",era:"535–475 BC",civ:"Greece",cat:["philosophy","virtue"]},
// === EASTERN ===
{q:"The supreme art of war is to subdue the enemy without fighting.",a:"Sun Tzu",era:"544–496 BC",civ:"China",cat:["war","strategy"]},
{q:"All warfare is based on deception.",a:"Sun Tzu",era:"544–496 BC",civ:"China",cat:["war","strategy"]},
{q:"In the midst of chaos, there is also opportunity.",a:"Sun Tzu",era:"544–496 BC",civ:"China",cat:["strategy"]},
{q:"Know thy enemy and know yourself; in a hundred battles you will never be in peril.",a:"Sun Tzu",era:"544–496 BC",civ:"China",cat:["war","strategy"]},
{q:"Appear weak when you are strong, and strong when you are weak.",a:"Sun Tzu",era:"544–496 BC",civ:"China",cat:["strategy","war"]},
{q:"The greatest victory is that which requires no battle.",a:"Sun Tzu",era:"544–496 BC",civ:"China",cat:["war","strategy"]},
{q:"Opportunities multiply as they are seized.",a:"Sun Tzu",era:"544–496 BC",civ:"China",cat:["strategy","ambition"]},
{q:"Let your plans be dark and impenetrable as night, and when you move, fall like a thunderbolt.",a:"Sun Tzu",era:"544–496 BC",civ:"China",cat:["war","strategy"]},
{q:"Every battle is won or lost before it is ever fought.",a:"Sun Tzu",era:"544–496 BC",civ:"China",cat:["war","strategy"]},
{q:"He who conquers himself is the mightiest warrior.",a:"Confucius",era:"551–479 BC",civ:"China",cat:["virtue","philosophy"]},
{q:"Our greatest glory is not in never falling, but in rising every time we fall.",a:"Confucius",era:"551–479 BC",civ:"China",cat:["virtue"]},
{q:"It does not matter how slowly you go as long as you do not stop.",a:"Confucius",era:"551–479 BC",civ:"China",cat:["virtue","ambition"]},
{q:"Before you embark on a journey of revenge, dig two graves.",a:"Confucius",era:"551–479 BC",civ:"China",cat:["philosophy","strategy"]},
{q:"The man who moves a mountain begins by carrying away small stones.",a:"Confucius",era:"551–479 BC",civ:"China",cat:["virtue","ambition"]},
// === MEDIEVAL / RENAISSANCE ===
{q:"The end justifies the means.",a:"Niccolò Machiavelli",era:"1469–1527",civ:"Florence",cat:["strategy","leadership"]},
{q:"It is better to be feared than loved, if you cannot be both.",a:"Niccolò Machiavelli",era:"1469–1527",civ:"Florence",cat:["leadership","strategy"]},
{q:"Everyone sees what you appear to be, few experience what you really are.",a:"Niccolò Machiavelli",era:"1469–1527",civ:"Florence",cat:["strategy","philosophy"]},
{q:"The lion cannot protect himself from traps, and the fox cannot defend himself from wolves. One must therefore be a fox to recognize traps, and a lion to frighten wolves.",a:"Niccolò Machiavelli",era:"1469–1527",civ:"Florence",cat:["strategy","leadership"]},
{q:"Never was anything great achieved without danger.",a:"Niccolò Machiavelli",era:"1469–1527",civ:"Florence",cat:["ambition","strategy"]},
{q:"Men are driven by two principal impulses, either by love or by fear.",a:"Niccolò Machiavelli",era:"1469–1527",civ:"Florence",cat:["leadership","philosophy"]},
{q:"Where there is a great will there are no great difficulties.",a:"Niccolò Machiavelli",era:"1469–1527",civ:"Florence",cat:["ambition"]},
// === NAPOLEONIC ===
{q:"Impossible is a word to be found only in the dictionary of fools.",a:"Napoleon Bonaparte",era:"1769–1821",civ:"France",cat:["ambition","leadership"]},
{q:"History is a set of lies agreed upon.",a:"Napoleon Bonaparte",era:"1769–1821",civ:"France",cat:["philosophy"]},
{q:"A leader is a dealer in hope.",a:"Napoleon Bonaparte",era:"1769–1821",civ:"France",cat:["leadership"]},
{q:"Victory belongs to the most persevering.",a:"Napoleon Bonaparte",era:"1769–1821",civ:"France",cat:["war","virtue"]},
{q:"In politics, stupidity is not a handicap.",a:"Napoleon Bonaparte",era:"1769–1821",civ:"France",cat:["philosophy","empire"]},
{q:"Four hostile newspapers are more to be feared than a thousand bayonets.",a:"Napoleon Bonaparte",era:"1769–1821",civ:"France",cat:["strategy","empire"]},
{q:"Never interrupt your enemy when he is making a mistake.",a:"Napoleon Bonaparte",era:"1769–1821",civ:"France",cat:["strategy","war"]},
{q:"The battlefield is a scene of constant chaos. The winner will be the one who controls that chaos.",a:"Napoleon Bonaparte",era:"1769–1821",civ:"France",cat:["war","leadership"]},
{q:"Glory is fleeting, but obscurity is forever.",a:"Napoleon Bonaparte",era:"1769–1821",civ:"France",cat:["ambition","philosophy"]},
{q:"Courage is like love; it must have hope for nourishment.",a:"Napoleon Bonaparte",era:"1769–1821",civ:"France",cat:["virtue","philosophy"]},
{q:"There are only two forces in the world, the sword and the spirit. In the long run the sword will always be conquered by the spirit.",a:"Napoleon Bonaparte",era:"1769–1821",civ:"France",cat:["philosophy","war"]},
{q:"Men are moved by two levers only: fear and self-interest.",a:"Napoleon Bonaparte",era:"1769–1821",civ:"France",cat:["leadership","strategy"]},
{q:"An army marches on its stomach.",a:"Napoleon Bonaparte",era:"1769–1821",civ:"France",cat:["war","strategy"]},
{q:"If you want a thing done well, do it yourself.",a:"Napoleon Bonaparte",era:"1769–1821",civ:"France",cat:["leadership","virtue"]},
{q:"The world suffers a lot. Not because of the violence of bad people, but because of the silence of good people.",a:"Napoleon Bonaparte",era:"1769–1821",civ:"France",cat:["virtue","philosophy"]},
// === MODERN ===
{q:"Speak softly and carry a big stick.",a:"Theodore Roosevelt",era:"1858–1919",civ:"United States",cat:["leadership","strategy"]},
{q:"Do what you can, with what you have, where you are.",a:"Theodore Roosevelt",era:"1858–1919",civ:"United States",cat:["virtue","ambition"]},
{q:"It is not the critic who counts; not the man who points out how the strong man stumbles. The credit belongs to the man who is actually in the arena.",a:"Theodore Roosevelt",era:"1858–1919",civ:"United States",cat:["virtue","ambition"]},
{q:"Believe you can and you're halfway there.",a:"Theodore Roosevelt",era:"1858–1919",civ:"United States",cat:["ambition"]},
{q:"In any moment of decision, the best thing you can do is the right thing. The worst thing you can do is nothing.",a:"Theodore Roosevelt",era:"1858–1919",civ:"United States",cat:["leadership","virtue"]},
{q:"We shall fight on the beaches, we shall fight on the landing grounds, we shall never surrender.",a:"Winston Churchill",era:"1874–1965",civ:"United Kingdom",cat:["war","leadership"]},
{q:"History will be kind to me, for I intend to write it.",a:"Winston Churchill",era:"1874–1965",civ:"United Kingdom",cat:["ambition","leadership"]},
{q:"Success is not final, failure is not fatal: it is the courage to continue that counts.",a:"Winston Churchill",era:"1874–1965",civ:"United Kingdom",cat:["virtue","ambition"]},
{q:"If you're going through hell, keep going.",a:"Winston Churchill",era:"1874–1965",civ:"United Kingdom",cat:["virtue"]},
{q:"You have enemies? Good. That means you've stood up for something, sometime in your life.",a:"Winston Churchill",era:"1874–1965",civ:"United Kingdom",cat:["virtue","leadership"]},
{q:"Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.",a:"Winston Churchill",era:"1874–1965",civ:"United Kingdom",cat:["virtue","leadership"]},
{q:"The price of greatness is responsibility.",a:"Winston Churchill",era:"1874–1965",civ:"United Kingdom",cat:["leadership","virtue"]},
{q:"Nearly all men can stand adversity, but if you want to test a man's character, give him power.",a:"Abraham Lincoln",era:"1809–1865",civ:"United States",cat:["leadership","philosophy"]},
{q:"The best way to predict your future is to create it.",a:"Abraham Lincoln",era:"1809–1865",civ:"United States",cat:["ambition"]},
{q:"Whatever you are, be a good one.",a:"Abraham Lincoln",era:"1809–1865",civ:"United States",cat:["virtue"]},
{q:"Give me six hours to chop down a tree and I will spend the first four sharpening the axe.",a:"Abraham Lincoln",era:"1809–1865",civ:"United States",cat:["strategy","virtue"]},
// === FAITH ===
{q:"For what shall it profit a man, if he shall gain the whole world, and lose his own soul?",a:"Jesus Christ (Mark 8:36)",era:"~4 BC–33 AD",civ:"Judea",cat:["faith","philosophy"]},
{q:"The truth shall set you free.",a:"Jesus Christ (John 8:32)",era:"~4 BC–33 AD",civ:"Judea",cat:["faith","philosophy"]},
{q:"Love your enemies, bless them that curse you.",a:"Jesus Christ (Matthew 5:44)",era:"~4 BC–33 AD",civ:"Judea",cat:["faith","virtue"]},
{q:"With God all things are possible.",a:"Jesus Christ (Matthew 19:26)",era:"~4 BC–33 AD",civ:"Judea",cat:["faith"]},
{q:"Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.",a:"Jesus Christ (Matthew 7:7)",era:"~4 BC–33 AD",civ:"Judea",cat:["faith"]},
{q:"In this sign, conquer.",a:"Constantine I",era:"272–337 AD",civ:"Roman Empire",cat:["faith","empire","war"]},
{q:"Faith is taking the first step even when you can't see the whole staircase.",a:"Traditional proverb",era:"Classical",civ:"Various",cat:["faith","virtue"]},
{q:"I can do all things through Christ which strengtheneth me.",a:"Paul (Philippians 4:13)",era:"~5–67 AD",civ:"Roman Empire",cat:["faith","virtue"]},
{q:"Put on the whole armor of God, that ye may be able to stand against the wiles of the devil.",a:"Paul (Ephesians 6:11)",era:"~5–67 AD",civ:"Roman Empire",cat:["faith","virtue"]},
{q:"For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.",a:"Paul (2 Timothy 1:7)",era:"~5–67 AD",civ:"Roman Empire",cat:["faith","virtue"]},
{q:"Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God will be with you wherever you go.",a:"Joshua 1:9",era:"~1400 BC",civ:"Israel",cat:["faith","virtue"]},
{q:"The fear of the Lord is the beginning of wisdom.",a:"Proverbs 9:10",era:"~950 BC",civ:"Israel",cat:["faith","philosophy"]},
{q:"Iron sharpeneth iron; so a man sharpeneth the countenance of his friend.",a:"Proverbs 27:17",era:"~950 BC",civ:"Israel",cat:["faith","virtue"]},
{q:"Where there is no vision, the people perish.",a:"Proverbs 29:18",era:"~950 BC",civ:"Israel",cat:["faith","leadership"]},
{q:"To everything there is a season, and a time to every purpose under the heaven.",a:"Ecclesiastes 3:1",era:"~950 BC",civ:"Israel",cat:["faith","philosophy"]},
// === ASSORTED HISTORICAL ===
{q:"He who has a why to live for can bear almost any how.",a:"Friedrich Nietzsche",era:"1844–1900",civ:"Germany",cat:["philosophy"]},
{q:"What does not kill me makes me stronger.",a:"Friedrich Nietzsche",era:"1844–1900",civ:"Germany",cat:["virtue","philosophy"]},
{q:"God is dead. God remains dead. And we have killed him.",a:"Friedrich Nietzsche",era:"1844–1900",civ:"Germany",cat:["philosophy"]},
{q:"He who fights with monsters should look to it that he himself does not become a monster.",a:"Friedrich Nietzsche",era:"1844–1900",civ:"Germany",cat:["philosophy","virtue"]},
{q:"There is no greater agony than bearing an untold story inside you.",a:"Friedrich Nietzsche",era:"1844–1900",civ:"Germany",cat:["philosophy"]},
{q:"The individual has always had to struggle to keep from being overwhelmed by the tribe.",a:"Friedrich Nietzsche",era:"1844–1900",civ:"Germany",cat:["philosophy","virtue"]},
{q:"Man is something that shall be overcome. What have you done to overcome him?",a:"Friedrich Nietzsche",era:"1844–1900",civ:"Germany",cat:["philosophy","ambition"]},
{q:"Hard times create strong men. Strong men create good times. Good times create weak men. Weak men create hard times.",a:"G. Michael Hopf",era:"Modern",civ:"Various",cat:["philosophy","empire"]},
{q:"The only thing necessary for the triumph of evil is for good men to do nothing.",a:"attributed to Edmund Burke",era:"1729–1797",civ:"United Kingdom",cat:["virtue","philosophy"]},
{q:"Those who would give up essential liberty, to purchase a little temporary safety, deserve neither liberty nor safety.",a:"Benjamin Franklin",era:"1706–1790",civ:"United States",cat:["philosophy","empire"]},
{q:"The art of war is simple enough. Find out where your enemy is. Get at him as soon as you can. Strike him as hard as you can, and keep moving.",a:"Ulysses S. Grant",era:"1822–1885",civ:"United States",cat:["war","strategy"]},
{q:"In war there is no substitute for victory.",a:"Douglas MacArthur",era:"1880–1964",civ:"United States",cat:["war"]},
{q:"Old soldiers never die; they just fade away.",a:"Douglas MacArthur",era:"1880–1964",civ:"United States",cat:["war","philosophy"]},
{q:"The only easy day was yesterday.",a:"US Navy SEALs motto",era:"Modern",civ:"United States",cat:["war","virtue"]},
{q:"Sweat saves blood, blood saves lives, and brains save both.",a:"Erwin Rommel",era:"1891–1944",civ:"Germany",cat:["war","strategy"]},
{q:"In a man-to-man fight, the winner is he who has one more round in his magazine.",a:"Erwin Rommel",era:"1891–1944",civ:"Germany",cat:["war"]},
{q:"The pen is mightier than the sword.",a:"Edward Bulwer-Lytton",era:"1803–1873",civ:"United Kingdom",cat:["philosophy","strategy"]},
{q:"Power tends to corrupt, and absolute power corrupts absolutely.",a:"Lord Acton",era:"1834–1902",civ:"United Kingdom",cat:["philosophy","empire"]},
{q:"The only thing we have to fear is fear itself.",a:"Franklin D. Roosevelt",era:"1882–1945",civ:"United States",cat:["leadership","virtue"]},
{q:"I have not yet begun to fight!",a:"John Paul Jones",era:"1747–1792",civ:"United States",cat:["war","virtue"]},
{q:"The tree of liberty must be refreshed from time to time with the blood of patriots and tyrants.",a:"Thomas Jefferson",era:"1743–1826",civ:"United States",cat:["empire","philosophy"]},
{q:"If you want to make enemies, try to change something.",a:"Woodrow Wilson",era:"1856–1924",civ:"United States",cat:["leadership","philosophy"]},
{q:"A people that values its privileges above its principles soon loses both.",a:"Dwight D. Eisenhower",era:"1890–1969",civ:"United States",cat:["philosophy","empire"]},
{q:"Plans are useless, but planning is indispensable.",a:"Dwight D. Eisenhower",era:"1890–1969",civ:"United States",cat:["strategy","war"]},
];

// Category list for filter UI
const QUOTE_CATEGORIES = ["all","war","leadership","philosophy","empire","faith","strategy","virtue","ambition"];

function getRandomQuote(category) {
    let pool = QUOTES;
    if (category && category !== "all") {
        pool = QUOTES.filter(q => q.cat.includes(category));
    }
    return pool[Math.floor(Math.random() * pool.length)];
}
